---
title: "YOUR TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
---

## Procedural outline
Turn on machines / heaters. Put mice in tailcuff room and let the room and mice acclimate to appropriate temperature for ~30-60 mins. Then, check cuffs for leaks. Put mice into restraints, and perform 5 acclimation cycles + 20 recorded cycles. Save your data to a thumb drive.

When placing mice into restraints,  
1. Quickly place nose cuff on to avoid letting them turn around/upside in the restraint
2. Make sure that you can see them breathing...  
3. Maximize tightness of fit *and* breathing 


## Run *process-data.R* first!
Be sure to fill in the proper Phases for each date in the excel spreadsheet and save it as an excel file with the proper extension *my_data.xlsx* in the folder *output/cleaned-data*


## Fill in the proper paths in *exec.R*

## Then hit Shift+Cmd+K :)

```{r load, echo=FALSE,message=TRUE,warning=FALSE}

# create data directory and and then a project subdirectory into which you dump csv files 
# THAT project directory will be used perpetually
fn_name <- "my_data.xlsx"

# NO "/" allowed in these variables!!
drug_name <- "sorafenib"
drug_dosage <- "300"
trial_num <- "3"
freq <- "mgkgd"



# pick your colors! only HEX
# For inspiration -- https://www.colorhexa.com/ 
veh_color <- "#1e81b0" # blue
tx_color <- "#ed9942" # orange


source("./scripts/process-data.R")
source("./scripts/main.R")
```

